//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodAccountingSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wood()
        {
            this.Wood_in_Storage = new HashSet<Wood_in_Storage>();
        }
    
        public int id_Wood { get; set; }
        public string name { get; set; }
        public int quality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wood_in_Storage> Wood_in_Storage { get; set; }
    }
}
