//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WoodAccountingSystem.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wood_in_Storage
    {
        public int id_Storage { get; set; }
        public int id_Wood { get; set; }
        public Nullable<int> volume_wood { get; set; }
    
        public virtual Storage Storage { get; set; }
        public virtual Wood Wood { get; set; }
    }
}
